### PR TITLE
Added possibility to use svg icons by name instead of urls

### PR DESCRIPTION
**Pull request by yckmciaiy**
if previously loaded by registry

### CODE REVIEW

**Comment by czeckd** [comment]
What use case is this solving? Is this more of a developer convenience feature?

**Comment by yckmciaiy** [comment]
The idea is that you can incapsulate actual urls from templates, as well as centralize svgs management. So yes, more like a developers feature.

**Comment by yckmciaiy** [comment]
As I've mentioned in #56 this behavior is similar to how it is done in angular material icon, and requires url instead of svg data as in addSvg function of your icon registry

**Comment by yckmciaiy** [comment]
So @czeckd should I expect it to be merged someday?

**Comment by czeckd** [comment]
@yckmciaiy — Yes, but due to Universal support, the pull req now has conflicts. Do you have time to update your pull?

**Comment by yckmciaiy** [comment]
@czeckd — Done resolving conflicts, but with adding universal support, it looks to me, that it is quiet inconsistent with current variables naming after I've changed inner code of loadSvg function. Would consider reworking it a bit in future.

**Comment by yckmciaiy** [comment]
@czeckd any comments?

**Comment by czeckd** [comment]
@yckmciaiy It's good to go, will get it merged and on npm this week. Thanks!

**Comment by yckmciaiy** [comment]
Thank you! :+1:

**Comment by yckmciaiy** [comment]
@czeckd hey man, sorry to bother, just checking, if there are any updates?

**Comment by czeckd** [comment]
Should be there now.

**Pull request merged**
