### PR TITLE
Added support to apply css classes of host component to content of svg-icon

### PR DESCRIPTION
**Pull request by Settler**
Hi!

First of all - thank you for great component!
This PR extends component to accept CSS styles from component for SVG content, where svg-icon is placed.
Also this approach gives opportunity to create animations or hover\focus effects for parts of SVG.

For example:
Component HTML:
```HTML
<h1>Css Test</h1>
<svg-icon src="/path/to/some.svg"></svg-icon>
```
Component CSS:
```CSS
svg-icon svg path {
    fill: white;
}
svg-icon:hover svg path {
    fill: black;
}
````

The problem that this PR solves:
Component where svg-icon is placed marks all its children by **_ngcontent** attribute, and it modifies CSS classes to select only elements with this attribute.
Compiled HTML and CSS will looks like:
```HTML
<h1 _ngcontent-c0>Css Test</h1>
<svg-icon _ngcontent-c0 src="/path/to/some.svg">
    <svg>
        <path d="..."></path>
    </svg>
</svg-icon>
```
```CSS
svg-icon[_ngcontent-c0] svg[_ngcontent-c0] path[_ngcontent-c0] {
    fill: white;
}
svg-icon[_ngcontent-c0]:hover svg[_ngcontent-c0] path[_ngcontent-c0] {
    fill: black;
}
````
So, CSS classes will not be applied.
With this PR resulted HTML will looks like:
```HTML
<h1 _ngcontent-c0>Css Test</h1>
<svg-icon _ngcontent-c0 src="/path/to/some.svg">
    <svg _ngcontent-c0>
        <path d="..." _ngcontent-c0></path>
    </svg>
</svg-icon>
```
And CSS classes will be applied successfully.
This looks like a hack, but svg-icon inlines SVG to component tree, so, I think, all children can be safely marked by component _ngcontent attribute. Motivation for this: "_When I (as developer) use svg-icon, I think that it inlines SVG into my component tree and I can perform all actions on SVG as well as on any other element on component tree_"

Comments and suggestions are welcome.
P.S. English is not my strong side, so I not edited README.md. Need help here.

### CODE REVIEW

**Comment by czeckd** [comment]
I'm thinking it may be a better approach to model using classes on the svg-icon like [ngClass](https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_class.ts) does. This was the approach I did with the `svgStyle` attribute. (I adapted [ngStyle](https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_style.ts) into the svg-icon component.) That way the class is applied directly to the actual svg directly. What do you think?

**Comment by Settler** [comment]
Hi @czeckd! Nice to read you :)

If we apply classes to `<svg>`, then inner elements (`<path>`, `<polygon>`, etc) will inherit properties from that classes. This approach have two limitations:
1) If inner elements have attributes (fill, stroke, opacity) which set explicit, then properties from styles will not be applied.
2) If I want to apply different colors for different SVG parts, or I want to animate different parts of SVG, then I can't do that from classes applied to parent `<svg>` element.

**Comment by czeckd** [comment]
Would you please extend the demo app to demonstrate what you mean by "apply different colors for different SVG parts, or I want to animate different parts of SVG"? 

I am having trouble visualizing what you mean.

**Comment by Settler** [comment]
You can view example here:
https://teropa.info/blog/2016/12/12/graphics-in-angular-2.html#css-transitions-and-animations

**Comment by jiarongxu** [comment]
@czeckd We got a similar situation as @Settler. Need to style a <path> tag inside of svg for different conditions. Without adding _ngcontent-x attributes to elements inside svg, we can't style the path tag by component styles. The only way is to use open scope css. Could you consider to merge the pull request Thank you.

**Comment by czeckd** [comment]
@jiarongxu I'd like to see the demo app extended to show this working before the merge. I do not have the cycles to update the demo at the moment to do it myself.

**Comment by Settler** [comment]
@czeckd, I'm going to try to update demo app in next few days.

**Comment by Settler** [comment]
I've updated demo app. It looks like this now:
image

**Comment by czeckd** [comment]
@Settler Thank you! I'll get this merged this weekend.

**Comment by czeckd** [comment]
@Settler — Just a head's up I renamed supportCss to applyCss and changed the default to be false. This will be in angular-svg-icon@7.2.0.

**Comment by Settler** [comment]
@czeckd – Cool! Thnx!

**Pull request merged**
