### PR TITLE
Standalone component with provide function support

### LINKED ISSUE #146: AngularSvgIcon in only standalone angular application
I think it's worth to add to readme, that we have different way of inititalizing AngularSvgIcon in standalone application.

To do that you need to add in your main.ts:

```
  providers: [
...
    importProvidersFrom(AngularSvgIconModule.forRoot(), HttpClientModule),
  ],
```

### PR DESCRIPTION
**Pull request by sheikalthaf**
Convert svg icon component to standalone and create provide function for service

closes #146

### CODE REVIEW

**Comment by czeckd** [comment]
@sheikalthaf - Looks good. Thanks!

**Comment by sheikalthaf** [comment]
Any update on this

**Comment by czeckd** [comment]
@sheikalthaf - merged and released. Should be on npm now. Thanks again.

**Comment by sheikalthaf** [comment]
@czeckd thanks for the quick release. Implemented the latest release.

**Pull request merged**
